[general]
import = [
    "~/.config/alacritty/fonts/sf.toml",
    "~/.config/alacritty/themes/google.toml"
]

[terminal.shell]
program = "sh"
args = ["-c", " ~/.config/tmux/scripts/launch.sh"]

[window]
decorations = "none"
opacity = 0.75

[font]
size = 12.0
offset = { y = 9 }

[colors.primary]
background = "#000000"

