[shell]
program = "/usr/bin/tmux"

[window]
startup_mode = "Fullscreen"
opacity = 0.90

[font]
normal = { family = "Cartograph CF", style = "Regular" }
bold = { family = "Cartograph CF", style = "Bold" }
italic = { family = "Cartograph CF", style = "Italic" }
bold_italic = { family = "Cartograph CF", style = "Bold Italic" }
size = 12.0
offset = { y = 5 }
