[general]
import = [
    "~/.config/alacritty/fonts/hasklug.toml",
    "~/.config/alacritty/themes/zenburn.toml"
]

[terminal.shell]
program = "/usr/bin/tmux"

[window]
decorations = "none"
opacity = 0.95

[font]
size = 12.0
offset = { y = 9 }

[colors.primary]
background = "#000000"

