[general]
import = [
    "~/.config/alacritty/fonts/sf.toml",
    "~/.config/alacritty/themes/rose_pine.toml"
]

[terminal.shell]
program = "sh ~/.config/tmux/scripts/launch.sh"

[window]
decorations = "none"
opacity = 0.90

[font]
size = 12.0
offset = { y = 9 }

[colors.primary]
background = "#000000"

