[shell]
program = "/usr/bin/tmux"

[window]
startup_mode = "Fullscreen"
opacity = 0.85

[font]
size = 12.0
offset = { y = 5 }

normal      = { family = "Cartograph CF", style = "Regular" }
bold        = { family = "Cartograph CF", style = "Bold" }
italic      = { family = "Cartograph CF", style = "Italic" }
bold_italic = { family = "Cartograph CF", style = "Bold Italic" }

# normal      = { family = "FiraCode Nerd Font", style = "Retina"}
# bold        = { family = "FiraCode Nerd Font", style = "Bold"}
# italic      = { family = "FiraCode Nerd Font", style = "SemiBold"}
# bold_italic = { family = "FiraCode Nerd Font", style = "Bold"}
