[font]
normal      = { family = "FiraCode Nerd Font", style = "Retina"}
bold        = { family = "FiraCode Nerd Font", style = "Bold"}
italic      = { family = "FiraCode Nerd Font", style = "SemiBold"}
bold_italic = { family = "FiraCode Nerd Font", style = "Bold"}
