FROM alpine:3.20.3

ENV CPM_SOURCE_CACHE=/root/.cache/CPM

RUN apk add --no-cache \
    build-base \
    cmake \
    samurai \
    ca-certificates \
    openssl-dev \
    openssl-libs-static \
    sqlite-dev \
    postgresql-dev \
    git
